import { existsSync } from "node:fs";
import { readdir, readFile } from "node:fs/promises";
import path from "node:path";
import { sha256 } from "./geo.mjs";
import { INDIA_OUTLINE_FILE, META_FILE, STATES_DIR, WARDS_DIR, stateDir } from "./paths.mjs";

export async function readJson(file) {
  return JSON.parse(await readFile(file, "utf8"));
}

export async function listStateCodes() {
  if (!existsSync(STATES_DIR)) {
    return [];
  }
  const entries = await readdir(STATES_DIR, { withFileTypes: true });
  return entries
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name.toUpperCase())
    .sort();
}

/**
 * Loads one state: state.json, outline, and every ac/{n}.geojson.
 * `files` keeps the file name of each constituency for error messages.
 */
export async function loadState(code) {
  const dir = stateDir(code);
  const statePath = path.join(dir, "state.json");
  const state = existsSync(statePath) ? await readJson(statePath) : null;
  const outlinePath = path.join(dir, "outline.geojson");
  const outline = existsSync(outlinePath) ? await readJson(outlinePath) : null;

  const acDir = path.join(dir, "ac");
  const names = existsSync(acDir)
    ? (await readdir(acDir)).filter((name) => name.endsWith(".geojson"))
    : [];
  const constituencies = [];
  for (const name of names) {
    const file = path.join(acDir, name);
    const raw = await readFile(file, "utf8");
    constituencies.push({ file, name, raw, feature: JSON.parse(raw) });
  }
  constituencies.sort(
    (a, b) =>
      (a.feature.properties?.acNo ?? 0) - (b.feature.properties?.acNo ?? 0),
  );
  return { code: code.toUpperCase(), dir, state, outline, constituencies };
}

/**
 * Content hash of a state's source data. Formatting-independent: hashes the
 * parsed objects, so re-indenting a file doesn't bump the version.
 */
export function stateContentHash(loaded) {
  const parts = loaded.constituencies.map(({ feature }) => JSON.stringify(feature));
  parts.push(JSON.stringify(loaded.outline));
  return sha256(parts.join("\n"));
}

export async function loadMeta() {
  return readJson(META_FILE);
}

export async function loadIndiaOutline() {
  return readJson(INDIA_OUTLINE_FILE);
}

export function indiaOutlineHash(outline) {
  return sha256(JSON.stringify(outline));
}

/** Lists ward cities: data/wards/{state}/{city}/ */
export async function listWardCities() {
  if (!existsSync(WARDS_DIR)) {
    return [];
  }
  const out = [];
  for (const stateEntry of await readdir(WARDS_DIR, { withFileTypes: true })) {
    if (!stateEntry.isDirectory()) {
      continue;
    }
    const stateFolder = path.join(WARDS_DIR, stateEntry.name);
    for (const cityEntry of await readdir(stateFolder, { withFileTypes: true })) {
      if (!cityEntry.isDirectory()) {
        continue;
      }
      const dir = path.join(stateFolder, cityEntry.name);
      out.push({
        state: stateEntry.name,
        city: cityEntry.name,
        dir,
        ulbFile: path.join(dir, "ulb.json"),
        wardsFile: path.join(dir, "wards.geojson"),
      });
    }
  }
  return out.sort((a, b) => a.dir.localeCompare(b.dir));
}

/** district name -> sorted acNos, plus constituencies with no district. */
export function deriveDistricts(regionCode, features) {
  const byDistrict = new Map();
  const unassigned = [];
  for (const feature of features) {
    const { districtName, acNo } = feature.properties;
    if (!districtName) {
      unassigned.push(acNo);
      continue;
    }
    if (!byDistrict.has(districtName)) {
      byDistrict.set(districtName, []);
    }
    byDistrict.get(districtName).push(acNo);
  }
  return {
    regionCode,
    generated: "Generated by `npm run build`. Do not edit; change districtName in ac/*.geojson instead.",
    districts: [...byDistrict.entries()]
      .sort((a, b) => a[0].localeCompare(b[0]))
      .map(([name, acNos]) => ({ name, acNos: acNos.sort((a, b) => a - b) })),
    unassigned: unassigned.sort((a, b) => a - b),
  };
}
